---
- name: Installing lamp Server on Ubuntu
  hosts: all
  become: yes
  tasks:
  - name: Installing apache and updating the server.
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: Installing php
    apt:
      name: php
      state: present
  - name: Installing libapache2-mod-php
    apt:
      name: libapache2-mod-php
      state: present
  - name: Installing php-mysql
    apt:
      name: php-mysql
      state: present
  - name: Installing php-cli
    apt:
      name: php-cli
      state: present
  - name: copying info.php to hosts
    copy:
      src: info.php
      dest: /var/www/html/info.php