---
- hosts: webservers
  become: yes
  tasks:
  - name: Install apache
    package:
      name: "{{package_name}}"
      state: present
  - name: Install apache
    package:
      name: "{{item}}"
      state: present
    loop: "{{php_packages}}"
    