---
- name: Installing lamp stack on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
  - name: install apache2
    apt:
      name: apache2
      state: present
      update_cache: yes
  - name: install libapache2-mod-php
    apt:
      name: libapache2-mod-php
      state: present
  - name: install php-mysql
    apt:
      name: php-mysql
      state: present
  - name: install php-cli
    apt:
      name: php-cli
      state: present
  - name: copy info.php file to ubuntu servers
    copy:
      src: info.php
      dest: /var/www/html/info.php

- name: Installing lamp stack on centos
  hosts: centos
  become: yes
  tasks:
  - name: installing httpd on centos
    yum:
      name: httpd
      state: present
      update_cache: yes
  - name: Enabling httpd service
    service:
      name: httpd
      enabled: yes
  - name: Starting httpd service
    service:
      name: httpd
      state: started
  - name: installing php
    yum:
      name: php
      state: present
  - name: installing php-mysql
    yum:
      name: php-mysql
      state: present
  - name: installing php-fpm
    yum:
      name: php-fpm
      state: present
  - name: copy info.php file to centos servers
    copy:
      src: info.php
      dest: /var/www/html/info.php
  