---
- hosts: webservers
  become: yes
  tasks:
  - name: Install apache
    package:
      name: "{{package_name}}"
      state: present
  - name: Install php
    package:
      name: "{{item}}"
      state: present
    loop: "{{php_packages}}"
  - name: copy info.php to remote server
    copy:
      src: info.php
      dest: /var/www/html/info.php
  - name: start and enable apache/httpd service
    service:
      name: "{{package_name}}"
      state: started
      enabled: yes
    