---
- name: Installing Lamp Stack on Centos
  hosts: all
  become: yes 
  tasks:
  - name: Installing apache2/httpd on centos
    yum:
      name: httpd
      state: present
  - name: Starting httpd/apache2 server
    systemd:
      name: httpd
      state: started
  - name: Installing php on centos
    yum:
      name: php
      state: present
  - name: Installing php-mysql on centos
    yum:
      name: php-mysql
      state: present
  - name: Restarting httpd server
    systemd:
      name: httpd
      state: restarted
  - name: Copying info.php file to host location
    copy:
      src: info.php
      dest: /var/www/html/info.php

- name: Deploying Tomcat application game-of-life on Centos server
  hosts: all
  become: true
  tasks:
  - name: Installing openjdk-8-jdk
    yum:
      name: java-1.8.0-openjdk
      state: present
  - name: Installing tomcat
    yum: 
      name: tomcat
      state: present
  - name: Installing tomcat-webapps
    yum: 
      name: tomcat-webapps
      state: present
  - name: Installing tomcat-admin-webapps
    yum: 
      name: tomcat-admin-webapps
      state: present
  - name: starting tomcat server
    systemd:
      name: tomcat
      state: started
  - name: Downloading game of life war file
    get_url:
      url: https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
      dest: /var/lib/tomcat/webapps/gameoflife.war


  
    
