---
- name: Installing Lamp Server on Centos
  hosts: all
  become: yes
  tasks:
  - name: Installing apache2/httpd on centos
    yum:
      name: httpd
      state: present
  - name: Starting httpd/apache2 server
    systemd:
      name: httpd
      state: started
      
    
