---
  name: Deploying Tomcat application game-of-life
  hosts: all
  become: yes
  tasks:
    - name: Installing openjdk-8-jdk
      apt:
        name: openjdk-8-jdk
        update_cache: yes
        state: present
    - name: Installing tomcat8
      apt:
        name: tomcat8
        state: present
    - name: Downloading application from aws s3 to webapps of tomcat
      get_url:
        url: https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war
        dest: /var/lib/tomcat8/webapps/gameoflife.war