---
- name: variables demo
  hosts: ubuntu
  become: yes
  tasks:
  - name: print statements using debug
    debug:
      var: ansible_host
  - name: print statements using debug
    debug:
      msg: "Ansible_User = {{ ansible_user }}"

