---
- name: variables demo
  hosts: webserver
  become: yes
  tasks:
  - name: print statements using debug
    debug:
      var: ansible_host
  - name: print statements using debug
    debug:
      msg: "Ansible_Port = {{ ansible_port }}  && Ansible_User = {{ ansible_user }}"

