---
- name: installing git, tree
  hosts: all
  become: yes
  tasks:
  - name: installing git using package module
    package:
      name: git
      state: present
  - name: installing tree using package module
    package:
      name: tree
      state: present
  - name: installing nano using package module
    package:
      name: nano
      state: present