---
- name: installing git, tree
  hosts: all
  become: yes
  tasks:
  - name: installing git using package module
    package:
      name: git
      state: present
  - name: installing tree using package module
    package:
      name: tree
      state: present
  - name: installing nano using package module
    package:
      name: nano
      state: present

- name: installing apache on centos
  hosts: centos
  become: yes
  tasks:
  - name: install apache on centos
    yum:
      name: httpd
      state: present
  - name: enabling apache on centos
    service:
      name: httpd
      enabled: yes
  - name: starting apache on centos
    service:
      name: httpd
      state: started
      
- name: installing java on ubuntu
  hosts: ubuntu
  become: yes
  tasks:
  - name: Installing java on ubuntu
    package:
      name: openjdk-8-jdk
      state: yes
