---
- name: Testing command module
  hosts: appservers
  become: yes
  tasks:
  - name: Test command module
    command: ls /opt/tomcat
    register: ls_cmd_status
    when: ansible_facts['distribution'] == "Ubuntu"


