---
- name: Installing tomcat
  hosts: appservers
  become: yes
  tasks:
  - name: Install open jdk
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Adding group tomcat
    group:
      name: tomcat
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Adding user tomcat
    user:
      name: tomcat
      create_home: yes
      home: /opt/tomcat
      shell: /bin/false
      group: tomcat
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Download tomcat.zip file
    get_url:
      url: "https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.zip"
      dest: /tmp/apache-tomcat-8.5.61.zip
    when: ansible_facts['distribution'] == "Ubuntu"

    
    
