---
- name: Installing tomcat
  hosts: appservers
  become: yes
  tasks:
  - name: Install open jdk
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Install unzip 
    package:
      name: unzip
      state: present

  - name: Adding group tomcat
    group:
      name: tomcat
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Adding user tomcat
    user:
      name: tomcat
      create_home: yes
      home: /opt/tomcat
      shell: /bin/false
      group: tomcat
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"

  - name: Download tomcat.zip file
    get_url:
      url: https://downloads.apache.org/tomcat/tomcat-8/v8.5.61/bin/apache-tomcat-8.5.61.zip
      dest: /tmp/apache-tomcat-8.5.61.zip
    when: ansible_facts['distribution'] == "Ubuntu"
    
  # - name: Extract tomcat.zip
  #   unarchive:
  #     src: /tmp/apache-tomcat-8.5.61.zip
  #     dest: /opt/tomcat
  #   when: ansible_facts['distribution'] == "Ubuntu"

  # - name: create soft link 
  #   file:
  #     src: /opt/tomcat/apache-tomcat-8.5.61
  #     dest: /opt/tomcat/latest
  #     state: link
  #   when: ansible_facts['distribution'] == "Ubuntu"

  # - name: change file ownership
  #   file:
  #     path: /opt/tomcat
  #     owner: tomcat
  #     recurse: yes
  #   when: ansible_facts['distribution'] == "Ubuntu"

  # - name: Making scripts in bin directory executable
  #   file:
  #     path: "{{ item }}"
  #     mode : "u=+x"
  #   loop:
  #     - /opt/tomcat/latest/bin/catalina.sh
  #     - /opt/tomcat/latest/bin/ciphers.sh
  #     - /opt/tomcat/latest/bin/configtest.sh
  #     - /opt/tomcat/latest/bin/daemon.sh
  #     - /opt/tomcat/latest/bin/digest.sh
  #     - /opt/tomcat/latest/bin/setclasspath.sh
  #     - /opt/tomcat/latest/bin/shutdown.sh
  #     - /opt/tomcat/latest/bin/startup.sh
  #     - /opt/tomcat/latest/bin/tool-wrapper.sh
  #     - /opt/tomcat/latest/bin/version.sh
  #   when: ansible_facts['distribution'] == "Ubuntu"



