---
- name: Installing tomcat
  hosts: appservers
  become: yes
  tasks:
  - name: Install open jdk
    apt:
      name: openjdk-8-jdk
      update_cache: yes
      state: present
    when: ansible_facts['distribution'] == "Ubuntu"
  - name: Adding user
    user:
      name: tomcat
      home: /opt/tomcat
      shell: /bin/false
      group: tomcat
    when: ansible_facts['distribution'] == "Ubuntu"